# Generated by Django 4.2.4 on 2024-05-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('nameOrig', models.CharField(max_length=200)),
                ('oldBalanceOrig', models.DecimalField(decimal_places=2, max_digits=100)),
                ('newBalanceOrig', models.DecimalField(decimal_places=2, max_digits=100)),
                ('nameDest', models.CharField(max_length=200)),
                ('oldBalanceDest', models.CharField(max_length=200)),
                ('newBalanceDst', models.CharField(max_length=200)),
                ('isFraud', models.BooleanField()),
                ('isFlaggedFraud', models.BooleanField()),
            ],
        ),
    ]
