# Generated by Django 4.2.4 on 2024-05-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_paymentdetails_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='newBalanceDst',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='oldBalanceDest',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
