# Generated by Django 5.0.6 on 2024-05-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_alter_paymentdetails_newbalancedst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='newBalanceDst',
            new_name='newBalanceDest',
        ),
    ]
